#!/bin/sh
daftarlengkapku(){
rm daftarlengkap
mkdir -p pixmaps

for file in /usr/share/applications/*.desktop ;do
	while read line; do
		case $line in
			Name=*) N="${line[@]}"'|';;
			Icon=*) I="${line[@]##*=}" # remove all char before the last "="
				if [[ $I == *\/* ]];then # if there any "/" appear
					ln -sf $I pixmaps/;
				fi
				
				if [[ ${I: -4:1} == "." ]];then #last 4th char is dot?
					I=${I%.*} #remove extension and the dot also
				fi
				
				I=${I##*/}'|';; #remove all before the last "/" (remain only filename)
			Comment=*) C="${line[@]}"'|';;
			Exec=*) E="${line[@]}"'|';;
		esac
	done < $file
	echo $I$N$E$C${file##*/}>>daftarlengkap
	I="|";N="|";E="|";C="|";
done
}

daftarlengkapku


cari(){
	grep -i -e "Name=.*$e" -e "Comment=.*$e" -e "Exec=.*$e" daftarlengkap|sed 's/Name=//g; s/Comment=//g; s/Exec=//g' >hasilcari
	cut -d"|" -f1,2 hasilcari>cari_ikon_nama
	head -1 hasilcari|cut -d"|" -f4 >cari_komentar
	if [[ `cat cari_ikon_nama` == "" ]];then echo "dialog-warning|Hey "$HOSTNAME", You don't have that apps,Right?">cari_ikon_nama; fi
}
export -f cari

infocari(){
	if [[ "$t" != "" ]];then
		grep "|$t|" hasilcari |cut -d"|" -f4|sort -u>cari_komentar #cut -d"|" -f4 hasilcari>cari_komentar
	fi
}
export -f infocari

jalancari(){
	$(grep -i "$t" hasilcari|cut -d"|" -f3)
}
export -f jalancari

entercari(){
	$(head -1 hasilcari|cut -d"|" -f3)
}
export -f entercari


export XDG_DATA_DIRS=$(pwd):$XDG_DATA_DIRS
echo $XDG_DATA_DIRS
echo "find|What are you looking for, "$HOSTNAME"?"> cari_ikon_nama
echo "">cari_komentar
echo '
<window window_position="1">
  <vbox width-request="300">
	<entry>
		<action signal="changed">cari</action>
		<action signal="changed">refresh:t</action>
		<action signal="changed">refresh:info</action>
		<action signal="activate">entercari&</action>
		<action signal="activate">EXIT:exit</action>
		<variable>e</variable>
	</entry>
	<tree rules-hint="true" headers-visible="false" hover-selection="true">
		<height>500</height>
		<action signal="cursor_changed">infocari</action>
		<action signal="cursor_changed">refresh:info</action>
		<action signal="button-release-event">jalancari&</action>
		<action signal="button-release-event">EXIT:exit</action>
		<action>jalancari&</action>
		<action>EXIT:jalancari</action>
		<input file icon-column="0">cari_ikon_nama</input>
		<variable>t</variable>
	</tree>
	<text xalign="1">
		<input file>cari_komentar</input>
		<variable>info</variable>
	</text>
  </vbox>
</window>'>guicari
gtkdialog -f guicari
